name: cine_app
description: "Cine App es una aplicación de películas que te permite buscar películas, ver información de películas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  animate_do: ^4.2.0
  card_swiper: ^3.0.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^16.2.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.9.0
  drift_dev: ^2.29.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/
    - assets/profile.jpeg
    #apps
    - assets/apps/swapme.webp
    - assets/apps/swapme2.0.webp
    - assets/apps/tribbe.webp
    - assets/apps/chullacash.webp
    - assets/apps/chatsim.webp
    - assets/apps/count.webp

